<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Location;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            'agadir',
            'al hoceima',
            'beni mellal',
            'casablanca',
            'chefchaouen',
            'dakhla',
            'essaouira',
            'fes',
            'kenitra',
            'laayoune',
            'marrakech',
            'meknes',
            'mohammedia',
            'nador',
            'ouarzazate',
            'oujda',
            'rabat',
            'safi',
            'tanger',
            'taza',
            'tetouan',
            'Beni Mellal Airport',
            'Mohammed V International Aérport',
            'Dakhla Airport',
            'Hassan I Airport (Laâyoune Aérport)',


            // 'agadir',
            // 'ait benhaddou',
            // 'ait daoud',
            // 'ait ourir',
            // 'al hoceima',
            // 'amizmiz',
            // 'arfoud',
            // 'asilah',
            // 'azemmour',
            // 'azrou',
            // 'ben ahmed',
            // 'ben slimane',
            // 'benguerir',
            // 'beni mellal',
            // 'berkane',
            // 'berrechid',
            // 'bouskoura',
            // 'bouznika',
            // 'casablanca',
            // 'chefchaouen',
            // 'chemaia',
            // 'chichaoua',
            // 'dakhla',
            // 'dar bouazza',
            // 'demnate',
            // 'el hajeb',
            // 'el jadida',
            // 'errachidia',
            // 'essaouira',
            // 'fes',
            // 'figuig',
            // 'fnideq',
            // 'fquih ben salah',
            // 'guelmim',
            // 'guelta zemmour',
            // 'guercif',
            // 'had soualem',
            // 'harhoura',
            // 'ifrane',
            // 'imilchil',
            // 'imintanoute',
            // 'inezgane',
            // 'jerada',
            // 'kelaa sraghna',
            // 'kenitra',
            // 'khemis zemamra',
            // 'khemisset',
            // 'khenifra',
            // 'khouribga',
            // 'ksar el kebir',
            // 'laayoune',
            // 'lagouira',
            // 'larache',
            // 'marrakech',
            // 'martil',
            // 'mechra bel ksiri',
            // 'mediek ou mdiq',
            // 'mediouna',
            // 'mehdia',
            // 'meknes',
            // 'midelt',
            // 'mirleft',
            // 'missour',
            // 'mohammedia',
            // 'moulay bousselham',
            // 'mrirt',
            // 'nador',
            // 'oualidia',
            // 'ouarzazate',
            // 'ouezzane',
            // 'oujda',
            // 'oulad berhil',
            // 'oulad teïma',
            // 'rabat',
            // 'ras el ma',
            // 'rissani',
            // 'safi',
            // 'saidia',
            // 'sale',
            // 'sefrou',
            // 'settat',
            // 'sidi bou othmane',
            // 'sidi kacem',
            // 'sidi rahal',
            // 'sidi slimane',
            // 'skhirat',
            // 'smara',
            // 'taddert',
            // 'tahannaout',
            // 'taliouine',
            // 'talmest',
            // 'tamanar',
            // 'tamaris',
            // 'tameslouht',
            // 'tan-tan',
            // 'tanger',
            // 'taounate',
            // 'taourirte',
            // 'tarfaya',
            // 'taroudannt',
            // 'tata',
            // 'taza',
            // 'taznakht',
            // 'temara',
            // 'tetouan',
            // 'tiflet',
            // 'tinghir',
            // 'tiznit',
            // 'youssoufia',
            // 'zagora',
            // 'Al Massira Airport',
            // 'Al Cherif Al Idrissi Airport',
            // 'Ben Ben Slimane Airport',
            // 'Beni Mellal Airport',
            // 'Bouarfa Airport',
            // 'Mohammed V International Airport',
            // 'Tit Mellil Airport',
            // 'Moulay Ali Cherif Airport',
            // 'Essaouira (Mogador Airport',
            // 'Saïss Airport',
            // 'Guelmim Airport',
            // 'Ifrane Airport',
            // 'Marrakech-Menara Airport',
            // 'Nador Airport (Al Aroui Airport)',
            // 'Ouarzazate Airport',
            // 'Ouezzane Airport',
            // 'Angads Airport',
            // 'Tangier (Ibn Battouta Airport',
            // 'Tan Tan Airport (Plage Blanche Airport)',
            // 'Taroudannt Airport',
            // 'Taza Airport',
            // 'Sania Ramel Airport',
            // 'Zagora Airport',
            // 'Dakhla Airport',
            // 'Hassan I Airport (Laâyoune Airport)',
            // 'Smara Airport',
            // 'Inezgane Airport',
        ];

        foreach ($locations as $location) {
            Location::create(['name' => $location]);
        }

    }
}
